version: '3.4'

volumes:
  postgresdata: {}
  redisdata: {}
  kafkadata: {}

services:
  cm_presentation_web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44311
    ports:
      - "56559:80"
      - "44311:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    env_file:
      - variables.env

  cm_services_identity_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44300
    ports:
      - "19267:80"
      - "44300:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    env_file:
      - variables.env

  cm_services_exchange_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44369
    ports:
      - "64050:80"
      - "44369:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    env_file:
      - variables.env

  cm_services_wallet_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44373
    ports:
      - "36968:80"
      - "44373:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    env_file:
      - variables.env

  cm_services_wallet_views_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44343
    ports:
      - "62842:80"
      - "44343:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    env_file:
      - variables.env

  cm_infrastracture_sql:
    environment:
      - MSSQL_SA_PASSWORD=Test1990!
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  cm_infrastracture_postgres:
    environment:
      - POSTGRES_DB=cm_infrastracture_kongdb
      - POSTGRES_USER=cm
      - POSTGRES_PASSWORD=cm
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  cm_infrastracture_kong_migration:
    command: "kong migrations up"
    environment:
      - KONG_PG_HOST=cm_infrastracture_postgres
      - KONG_PG_DATABASE=cm_infrastracture_kongdb
      - KONG_PG_USER=cm
      - KONG_PG_PASSWORD=cm

  cm_infrastracture_kong:
    environment:
      - KONG_PG_HOST=cm_infrastracture_postgres
      - KONG_PG_DATABASE=cm_infrastracture_kongdb
      - KONG_PG_USER=cm
      - KONG_PG_PASSWORD=cm
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "18001:8001"
      - "18000:8000"

  cm_infrastracture_rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  cm_infrastracture_redis:
    ports:
      - "16379:6379"
    volumes:
      - redisdata:/data

  cm_infrastracture_zookeeper:
    ports:
      - "2181:2181"

  cm_infrastracture_kafka:
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CREATE_TOPICS="testtopic:1:1"
      - KAFKA_ZOOKEEPER_CONNECT=cm_infrastracture_zookeeper:2181
    volumes:
      - kafkadata:/kafka
